const soundEvTypes = [
    { label: '信号强度', value: 'Level_A' },
    { label: '基频占比', value: 'pf' },
    { label: '主频', value: 'fm' },
    { label: '主频占比', value: 'pm' },
    { label: '频谱复杂度', value: 'H' },
    { label: '奇次谐波占比', value: 'p_odd' },
    // {label: '奇次谐波占比(50Hz)', value: 'p_odd_50'},
    { label: '偶次谐波占比', value: 'p_even' },
    // {label: '偶次谐波占比(50Hz)', value: 'p_even50'},
    { label: '均方根', value: 'rms' },
    { label: '频段能量比', value: 'spFreRatio' },
    { label: '能量差异度', value: 'EDR' },
    // {label: '频率中心', value: 'spCentroid'},
    // {label: '频率峰度', value: 'spCrest'},
    // {label: '频率衰减', value: 'spDecrease'},
    // {label: '谱熵', value: 'spEntropy'},
    { label: '频率平坦度', value: 'spFlatness' },
    { label: '谱峭度', value: 'spKurtosis' },
    // {label: '谱偏度', value: 'spSkewness'},
    // {label: '谱斜率', value: 'spSlope'},
    // {label: '扩频', value: 'spSpread'},
];
const vibEvTypes = [
    { label: '信号强度', value: 'Level_A' },
    { label: '基频占比', value: 'pf' },
    { label: '频谱复杂度', value: 'H' },
    { label: '奇次谐波占比', value: 'p_odd' },
    { label: '偶次谐波占比', value: 'p_even' },
    { label: '均方根', value: 'rms' },
    { label: '频段能量比', value: 'spFreRatio' },
    // {label: '能量差异度', value: 'EDR'},
    // {label: '频率中心', value: 'spCentroid'},
    // {label: '频率峰度', value: 'spCrest'},
    // {label: '频率衰减', value: 'spDecrease'},
    // {label: '谱熵', value: 'spEntropy'},
    // {label: '频率平坦度', value: 'spFlatness'},
    // {label: '谱峭度', value: 'spKurtosis'},
    // {label: '谱偏度', value: 'spSkewness'},
    // {label: '谱斜率', value: 'spSlope'},
    // {label: '扩频', value: 'spSpread'},
    { label: '位移', value: 'd' },
    { label: '速度', value: 'v' },
    // {label: '加速度', value: 'a'},
]
